repositories:
  - path: ssh://${STORAGE_BOX_USER}@${STORAGE_BOX_HOST}:23/./borg/${COMPOSE_PROJECT_NAME}
    label: hetzner

source_directories:
  - /mautic/config
  - /db_dumps

encryption_passphrase: "${BORG_PASSPHRASE}"

compression: lz4

keep_daily: 7
keep_weekly: 4
keep_monthly: 3

checks:
  - name: repository
    frequency: 1 week
  - name: archives
    frequency: 1 week

commands:
  - before: action
    when: [create]
    run:
      - "echo '=== Začenjam backup: '$(date)"
      - "mysqldump --host=db --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --single-transaction --routines --triggers ${MYSQL_DATABASE} > /db_dumps/mautic_db.sql"
      - "echo '=== DB dump uspešen ==='"

  - after: action
    when: [create]
    run:
      - "echo '=== Backup uspešen: '$(date)"

  - after: error
    when: [create, prune, compact, check]
    run:
      - "echo '=== BACKUP NAPAKA: '$(date)"
